### ISSUE TITLE
Flashcard parsing sometimes dies

### ISSUE THREAD

**Issue by SverreNystad** [CogitoNTNU/TutorAI#97]
There have been cases when the parsing of flashcards fails and the program dies. This can be avoided. We should create som expectation handling for this.

```bash
tutorai-1  | Run 'python manage.py migrate' to apply them.
tutorai-1  | April 28, 2024 - 22:24:56
tutorai-1  | Django version 5.0.1, using settings 'tutorai.settings'
tutorai-1  | Starting development server at http://0.0.0.0:8000/
tutorai-1  | Quit the server with CONTROL-C.
tutorai-1  | 
tutorai-1  | [INFO] Request received...
tutorai-1  | request.data: <QueryDict: {'document': ['psykologi1_issuu_output.pdf'], 'start': ['76'], 'end': ['100']}>
tutorai-1  | [INFO] Trying to find relevant document
tutorai-1  | [INFO] Generating flashcards
tutorai-1  | Internal Server Error: /api/create-flashcards/
tutorai-1  | Traceback (most recent call last):
tutorai-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
tutorai-1  |     response = get_response(request)
tutorai-1  |                ^^^^^^^^^^^^^^^^^^^^^
tutorai-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
tutorai-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
tutorai-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tutorai-1  |   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper       
tutorai-1  |     return view_func(request, *args, **kwargs)
tutorai-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tutorai-1  |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
tutorai-1  |     return self.dispatch(request, *args, **kwargs)
tutorai-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tutorai-1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
tutorai-1  |     response = self.handle_exception(exc)
tutorai-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
tutorai-1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
tutorai-1  |     self.raise_uncaught_exception(exc)
tutorai-1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception   
tutorai-1  |     raise exc
tutorai-1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
tutorai-1  |     response = handler(request, *args, **kwargs)
tutorai-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tutorai-1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
tutorai-1  |     return func(*args, **kwargs)
tutorai-1  |            ^^^^^^^^^^^^^^^^^^^^^
tutorai-1  |   File "/code/flashcards/views.py", line 87, in create_flashcards
tutorai-1  |     flashcards: list[Flashcard] = process_flashcards(file_name, start, end)
tutorai-1  |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tutorai-1  |   File "/code/flashcards/flashcard_service.py", line 45, in process_flashcards
tutorai-1  |     flashcards.extend(future.result())
tutorai-1  |                       ^^^^^^^^^^^^^^^
tutorai-1  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
tutorai-1  |     return self.__get_result()
tutorai-1  |            ^^^^^^^^^^^^^^^^^^^
tutorai-1  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
tutorai-1  |     raise self._exception
tutorai-1  |   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
tutorai-1  |     result = self.fn(*self.args, **self.kwargs)
tutorai-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tutorai-1  |   File "/code/flashcards/flashcard_service.py", line 34, in process_page
tutorai-1  |     flashcards_from_page = generate_flashcards(page)
tutorai-1  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^
tutorai-1  |   File "/code/flashcards/text_to_flashcards.py", line 114, in generate_flashcards
tutorai-1  |     return parse_flashcard(response, page)
tutorai-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tutorai-1  |   File "/code/flashcards/text_to_flashcards.py", line 90, in parse_flashcard
tutorai-1  |     back=i[1].strip(),
tutorai-1  |          ~^^^
tutorai-1  | IndexError: list index out of range
tutorai-1  | [28/Apr/2024 22:25:54] "POST /api/create-flashcards/ HTTP/1.1" 500 150739
```

**Comment by SverreNystad** [comment]
The fix might be the problem. We need to monitor this future

**Comment by SverreNystad** [comment]
After monitoring this yoday the error has indeed sized to exist
